title: DiWeng
logo: /assets/img/profile.jpg
email: di.W@hotmail.com
description: Never Stop
education: Bachelor Degree Candidate
school: Beihang University
major: Information Management&Information System

link: http://zhaojichang.cn/
link_name: Jichang Zhao's Group
github_link: github.com/Di-Weng
theme: jekyll-theme-minimal
