title: DiWeng
logo: /assets/img/profile.jpg
description: Bachelor Degree Candidate
school: Beihang University
major: Information Management&Information System
email: di.W@hotmail.com
link: http://zhaojichang.cn/
link_name: Jichang Zhao's Group
github_link: github.com/Di-Weng
theme: jekyll-theme-minimal
