title: Di Weng
logo: /assets/img/profile.png
email: di.W@hotmail.com
description: One more step to touch the sky.
education: Postgraduate
school: University of Edinburgh
major: Data Science
google_analytics: UA-129698123-1
link: http://zhaojichang.cn/
link_name: Jichang Zhao's Group
github_link: github.com/Di-Weng
theme: jekyll-theme-minimal
